In [2]:
import pandas as pd
import numpy as np

In [3]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]]).T

a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
b

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [6]:
c = np.array([np.concatenate((a[i], b[i]), axis=0) for i in range(len(a))])
c

array([[1, 2, 3, 1, 4, 7],
       [4, 5, 6, 2, 5, 8],
       [7, 8, 9, 3, 6, 9]])

In [11]:
d = np.expand_dims(c, axis=2)
e = np.expand_dims(d, axis=3)
e

array([[[[1]],

        [[2]],

        [[3]],

        [[1]],

        [[4]],

        [[7]]],


       [[[4]],

        [[5]],

        [[6]],

        [[2]],

        [[5]],

        [[8]]],


       [[[7]],

        [[8]],

        [[9]],

        [[3]],

        [[6]],

        [[9]]]])

In [12]:
e.flatten()

array([1, 2, 3, 1, 4, 7, 4, 5, 6, 2, 5, 8, 7, 8, 9, 3, 6, 9])